LABEL_temp1="DIMM_A1"
MAXVALUE_temp1=125
MINVALUE_temp1=-40
WARNLO_temp1=80000
WARNHI_temp1=90000
CRITLO_temp1=-20000
CRITHI_temp1=95000


LABEL_temp3="DIMM_B1"
MAXVALUE_temp3=125
MINVALUE_temp3=-40
WARNLO_temp3=80000
WARNHI_temp3=90000
CRITLO_temp3=-20000
CRITHI_temp3=95000

