LABEL_temp3="CPU_Tcontrol"
MAXVALUE_temp3=125
MINVALUE_temp3=-40

LABEL_temp4="CPU_Tthrottle"
MAXVALUE_temp4=125
MINVALUE_temp4=-40

LABEL_temp5="CPU_Tjmax"
MAXVALUE_temp5=125
MINVALUE_temp5=-40

LABEL_temp6="CPU_Core0"
MAXVALUE_temp6=125
MINVALUE_temp6=-40

LABEL_temp7="CPU_Core1"
MAXVALUE_temp7=125
MINVALUE_temp7=-40

LABEL_temp8="CPU_Core2"
MAXVALUE_temp8=125
MINVALUE_temp8=-40

LABEL_temp10="CPU_Core4"
MAXVALUE_temp10=125
MINVALUE_temp10=-40

LABEL_temp11="CPU_Core5"
MAXVALUE_temp11=125
MINVALUE_temp11=-40

LABEL_temp12="CPU_Core6"
MAXVALUE_temp12=125
MINVALUE_temp12=-40

LABEL_temp14="CPU_Core8"
MAXVALUE_temp14=125
MINVALUE_temp14=-40

LABEL_temp15="CPU_Core9"
MAXVALUE_temp15=125
MINVALUE_temp15=-40
