LCONF_VERSION = "7"
BBPATH = "${TOPDIR}"
BBFILES ?= ""
BBLAYERS ?= " \
  /home/liun/workspace/andes2-openbmc/meta \
  /home/liun/workspace/andes2-openbmc/meta-aspeed \
  /home/liun/workspace/andes2-openbmc/meta-yunsilicon/meta-common \
  /home/liun/workspace/andes2-openbmc/meta-yunsilicon/meta-andes2 \
  "
